### ISSUE TITLE
User customizable timeout for RestClient requests

### ISSUE THREAD

**Issue by ahinz** [voucherifyio/voucherify-ruby-sdk#31]
We would like to reduce the max timeout from the default 60 seconds but the `RestClient` configuration doesn't seem to be accessible without monkey patching the client.

Would it be possible to poke through the timeout as a top-level config?

Thanks!

**Comment by lkulig** [comment]
Hey @ahinz, thanks for reaching out. For sure it is possible, I will do my best to release this new version as soon as possible. I will notify you once it is released.

**Comment by ahinz** [comment]
Awesome- thanks for the fast turnaround!
