### ISSUE TITLE
publish method should have the url of /publications

### ISSUE THREAD

**Issue by gvpmahesh** [voucherifyio/voucherify-ruby-sdk#39]
https://github.com/voucherifyio/voucherify-ruby-sdk/blob/master/lib/voucherify/service/distributions.rb#L20

**Comment by lkulig** [comment]
@gvpmahesh it cannot be actually changed since it will break other users integrations, since `publish` uses the `publish voucher` API endpoint (payloads are different between those two). So in order to prevent this I added new `create_publication` method
