### ISSUE TITLE
Voucherify::Utils.calculate_price does not consider the :amount_limit key

### ISSUE THREAD

**Issue by drinks** [voucherifyio/voucherify-ruby-sdk#46]
Percent-off vouchers with a cap amount set do not take that cap into consideration when calculating a discount.

From the util code here: https://github.com/voucherifyio/voucherify-ruby-sdk/blob/master/lib/voucherify/utils.rb#L37-L41 It's clear that the discount is a simple function of the percent off times the base price.

Happy to open a PR for this but I'm not sure of all the ways that a cap can come into play. Let me know if you need any more info or a reproduction case to move forward. Thanks!

**Comment by drinks** [comment]
Noting as well that it appears the other language SDKs exhibit this same defect; eg I don't see `:amount_limit` mentioned anywhere in their codebases.

**Comment by marcin-slezak** [comment]
I apologize for the delayed response. For your convenience, all necessary calculations are performed on the Voucherify API side and included in the API response. For example, in the [Validate Stackable Discounts](https://docs.voucherify.io/reference/validate-stacked-discounts) endpoint, the 'cap amount' is:

- taken into account when calculating prices, including `order.discount_amount`, `order.total_discount_amount`, `order.total_amount`, and `order.applied_discount_amount`.
- returned in `redeemables[x].result.discount.amount_limit`.
