### ISSUE TITLE
Add support for Get Member Activities in Loyalty program

### ISSUE THREAD

**Issue by darekg11** [voucherifyio/voucherify-ruby-sdk#48]
Add support for following API Endpoint:
https://docs.voucherify.io/reference#get-member-activities

**Comment by marcin-slezak** [comment]
Hi Darek, this link does not work anymore. Do you mean this endpoint: [List Member Activity](https://docs.voucherify.io/reference/list-member-activity) ?

**Comment by darekg11** [comment]
Well it is comment from 2020 : )
Endpoint mentioned by me was deprecated and removed recently.

Yup, the endpoint mentioned by you is the correct, if this is already added in version 5 of SDK, you can just close it
