### ISSUE TITLE
Ruby 2.7 deprecation warnings: Replace URL.encode 

### ISSUE THREAD

**Issue by kgillison** [voucherifyio/voucherify-ruby-sdk#50]
The Voucherify gem gives this warning under Ruby 2.7

`lib/voucherify/service/vouchers.rb:19: warning: URI.escape is obsolete`

[According to the docs](https://ruby-doc.org/stdlib-2.7.1/libdoc/uri/rdoc/URI/Escape.html#method-i-escape-label-Description) URI.encode is an alias for URI.escape, and 

_This method is obsolete and should not be used. Instead, use CGI.escape, URI.encode_www_form or URI.encode_www_form_component depending on your specific use case._

**Comment by lkulig** [comment]
@kgillison new version was pushed to rubygems. In case of any issue please drop us a message
