### ISSUE TITLE
Add support for "Qualification" actions

### ISSUE THREAD

**Issue by connor-odoherty** [voucherifyio/voucherify-ruby-sdk#56]
The Voucherify documentation describes an endpoint to ["Examine Qualification"](https://docs.voucherify.io/reference/create-qualification-request) that is not present in the Ruby SDK.

The Ruby SDK should expose this behavior through a `create_qualifications_request` method that takes a customer_id and optional context params, returning a list of campaigns said Customer is eligible for.

**Comment by marcin-slezak** [comment]
I apologize for the delayed response. We have released V5, which supports the [New Qualification API](https://docs.voucherify.io/reference/check-eligibility) endpoint: POST /v1/qualifications : https://github.com/voucherifyio/voucherify-ruby-sdk/blob/master/docs/QualificationsApi.md#check_eligibility
