### ISSUE TITLE
Cancelling an Order via Ruby

### ISSUE THREAD

**Issue by HyperDanTabist** [voucherifyio/voucherify-ruby-sdk#58]
I'm currently unable to cancel an order using the Ruby client. Cancelling orders using Curl works as expected, but making the request with the same request body using Ruby client doesn't work. Here are a couple of log ids

- log_0d446e83efc39dca2f (using Curl)
- log_0d44702edb9151d061 (using the Ruby client)

Since the requests are the same, I suspect the API is responding differently based on the user-agent or channel headers?

**Comment by darekg11** [comment]
Hello @HyperDanTabist could you provide code snippet involving the calls to updating order? Please remember to not show your API keys

**Comment by HyperDanTabist** [comment]
Hi @darekg11 ,
For the curl request
```
curl --request PUT \
  --url 'https://api.voucherify.io/v1/orders/ord_...' \
  --header 'Content-Type: application/json' \
  --header 'X-App-Id: ...' \
  --header 'X-App-Token: ...' \
  --data '{
	"status": "CANCELED"
}'
```

For the ruby code
```
client = Voucherify::Client.new(
          applicationId: application_id,
          clientSecretKey: client_secret_key
        )
client.orders.update(order_id, MultiJson.dump(status: :CANCELED)).with_indifferent_access
```

The log files contain the requests and responses received by the Voucherify API. I can see that Voucherify received the same request parameters for both Curl and Ruby, but the responses were different. The order was cancelled using Curl, but there were no changes with Ruby.
The only differences I can see is in the user-agent and channel request headers.
FYI: I'm currently using the sandbox environment.

**Comment by darekg11** [comment]
Hello @HyperDanTabist thanks for code snippet it helped.
The reason why it does not work in your case is that you are creating JSON via `MultiJson.dump(status: :CANCELED)` and then Voucherify's SDK is doing conversion to JSON once again:
https://github.com/voucherifyio/voucherify-ruby-sdk/blob/35cb9b29192dace82442274b13dade2f00f325de/lib/voucherify/service/orders.rb#L21

Please try following snippet:
```
client = Voucherify::Client.new(
          applicationId: application_id,
          clientSecretKey: client_secret_key
        )
client.orders.update(order_id, { status: :CANCELED });
```

**Comment by HyperDanTabist** [comment]
@darekg11 , 
I tested cancelling an order without manually converting to JSON and it worked.
Thank you for noticing the issue.

**Comment by darekg11** [comment]
@HyperDanTabist No problem, I will close this issue now.
